### ISSUE TITLE
Dialogs show up "between monitors" on a multi monitor setup

### ISSUE THREAD

**Issue by Pomax** [fontforge/designwithfontforge.com#103]
On my dual monitor setup, Fontforge will pop up dialogs in the center of "my total resolution" rather than centered on the monitor fontforge is open in.

**Comment by larsenwork** [comment]
Post this at fontforge/fontforge but do a search there first because I'm fairly certain it's a know issue.

**Comment by larsenwork** [comment]
ps: a quick solution is just to add a third monitor ;)

**Comment by Pomax** [comment]
I like this solution. Lord knows we have plenty of spares hooked up to raspberry pis and the like atm being underused...
