### ISSUE TITLE
Source Serif Pro has no italics, while the body text needs it

### ISSUE THREAD

**Issue by adrientetar** [fontforge/designwithfontforge.com#108]

**Comment by larsenwork** [comment]
Are we using it for anything but emphasise? - could maybe switch to bold instead of italics there.
We switched to SSP because it had a matching monospace for all the coding text. 
Ideally we need at serif font with regular, bold, italics and matching monospace

**Comment by davelab6** [comment]
@phoenixenero has solved this!
