### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by LeestKnown** [fontforge/designwithfontforge.com#117]
There are many typos in the book.

**Comment by LeestKnown** [comment]
Would you like me to document them or use the "pull request" button?

**Comment by jtanx** [comment]
A pull request would be great!

**Comment by LeestKnown** [comment]
Thanks for your reply Jeremy,
                                                 However, , I’m only up to chapter eleven. I have to read it all again. I’ll get back to you.
                                                 Kind Regards,
                                                                        Lee Walton
