### ISSUE TITLE
Reversed left and right side bearing in "A basic approach to spacing"?

### ISSUE THREAD

**Issue by madig** [fontforge/designwithfontforge.com#121]
The text says "the right side bearing of the 'o' can be used for the right side bearing of the 'c', 'd', 'e', and 'q'." but something tells me that it means the left side bearing, ditto for the rest of the bullet points.

**Comment by madig** [comment]
Oh, and the text says "the left side bearing of the 'n' can be used for the left side bearing of the 'b', 'h', 'k', 'm', 'p' and 'r'." and "the left side bearing of the 'o' can be used for the left side bearing of the 'b' and 'p'." -- so, uh, 'n' or 'o' for the left side bearing of 'b' and 'p'?

**Comment by jrbastien** [comment]
Fixed in the latest commit.  Feel free to re-open if you think it has not been corrected properly.
