### ISSUE TITLE
Typos and missing words in "What Is A Font?"

### ISSUE THREAD

**Issue by Markus00000** [fontforge/designwithfontforge.com#13]
In the second paragraph:

> These compomises mean that we can best think about typeface design as the creation a wonderful collection of letters but not as a collection of wonderful letters.

This should probably read:

> These **compromises** mean that we can best think about typeface design as the creation **of** a wonderful collection of letters but not as a collection of wonderful letters.

Fifth paragraph:

> they sometimes help detemine the technological contexts for which a font is suitable

This should probably read:

> they sometimes help **determine** the technological contexts for which a font is suitable

Under "ascender height":

> In example above, the x-heights have been matched in order to illustrate the relative difference in ascender heights.

This should probably read:

> In **the** example above, the x-heights have been matched in order to illustrate the relative difference in ascender heights.

**Comment by davelab6** [comment]
Thanks!
