### ISSUE TITLE
Kern tables aren't working 

### ISSUE THREAD

**Issue by evanisadesigner** [fontforge/designwithfontforge.com#131]
I'm using OSX 10.8.5.

When i save my typeface as an otf, install it, and type in Illustrator, the kern pairs aren't working correct.

For example, I have my A and V set at -300, but when I generate the font and install it, it shows up as 0 between the A and V when I type them.

Is there a certain way I need to save/export the font file so that these tables remain intact?

Thank you.

**Comment by JSColburn** [comment]
It's application specific. There's probably nothing wrong with your tables. 

I have had similar experiences with a ttf in which I use zero-advance, negative position, and kerning to implement vowel points in a conlang. MS Word (2013) for Windows (2007) does not honor my kerning tables in display or printing of my document, even though the text is a larger size than the "Kern at size" value. PowerPoint, WordPad, and Excel don't either. 

On the other hand, Notepad, MS Publisher (2013), Photoshop Elements (5.0), LibreOffice (6.0), Thunderbird (60.9.1), and Inkscape (0.91) all honor my kerning. Even Word does in displaying the dropdown styles list!

**Comment by ctrlcctrlv** [comment]
Per #199, not a documentation issue.
