### ISSUE TITLE
`lang` attributes for bodies of translated pages

### ISSUE THREAD

**Issue by Artoria2e5** [fontforge/designwithfontforge.com#136]
The `lang` attribute on HTML tags provides hints about content language, and help with machine readability (SEO & A11y) and text layout. Currently the attribute is not set for none of English and both Chineses.

Some compile-time tricks on `html-start.html` with `page.url` should be enough.

**Comment by jrbastien** [comment]
@Artoria2e5 , using `<html lang="{{ page.lang | default: site.lang | default: "en" }}">` in html-start.thml works well.  This requires though to add a lang: variable to the front matter.

My pages now looks like this:

```
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset='utf-8'>
    ...
```
I can make that change if everyone agrees.

**Comment by jrbastien** [comment]
I just found a simpler solution.  The language is also in the layout variable.  Ex: bookpage_fr-FR.
So no need to modify every frontmatter, I will just extract it from this variable.

`<html lang="{{ page.layout | slice: 9, 2 | default: "en" }}">`

**Comment by jrbastien** [comment]
@Artoria2e5 , you can close this issue if you are satisfied with its resolution.  The only page that does not get a lang attribute is [the US English Index](http://designwithfontforge.com/en-US/index.html).  I don't know why.  Jekyll does some strange things sometimes.  Perhaps, this is only in my cache.

**Comment by Artoria2e5** [comment]
I'm seeing a lang=en for that page on my side. Looks completely awesome.

**Comment by Artoria2e5** [comment]
Hmm, just one more thing. How about making the slice length `5` (or can it be made unbounded?) to include the country/variant part too?

**Comment by jrbastien** [comment]
Not sure if that it is necessary.  I know that they are two variation of the Chinese languages on DWFF already but I haven't found examples of sites where it is so specific.

**Comment by Artoria2e5** [comment]
[Chinese Wikipedia](https://zh.wikipedia.org) provides a dropdown menu that switches between different Chinese variants, and provides language tagging accordingly.

Here is the menu and what the text looks like [under zh-CN](https://zh.wikipedia.org/zh-cn/Wikipedia:首页?uselang=zh-cn):
![image](https://cloud.githubusercontent.com/assets/6459309/25412211/436181e6-29ef-11e7-95b9-60c6ff135265.png)

Here's the same thing [under zh-TW](https://zh.wikipedia.org/zh-tw/Wikipedia:首页?uselang=zh-tw):
![image](https://cloud.githubusercontent.com/assets/6459309/25412342/130c1e2e-29f0-11e7-8914-36003bcaa33f.png)

You will notice that two characters, 内 (left column, 特色内容) and 全 (main column under title, "自由百科全书/書") in the two pictures look vaguely the same but have differences in each representation. These characters are using the same Unicode code point across the two languages; it's the language tagging which told the browser to choose a suitable font that displays the subtle differences.
