### ISSUE TITLE
Showing update status for each section

### ISSUE THREAD

**Issue by marxo** [fontforge/designwithfontforge.com#14]
For someone who already read or will read the entire set of tutorials, it can be quite difficult to catch up when and what was edited, added, removed, etc.

I guess adding some kind of a notice in each section to show what's updated would be great.

**Comment by davelab6** [comment]
Hmm. Tricky to do with the current hosting set up (github) although there is a list of changes at https://github.com/fontforge/designwithfontforge.com/commits/gh-pages which if you click through to eg https://github.com/fontforge/designwithfontforge.com/commit/07654cd20737543dff398faf9b829079c9e56743 you see what was updated.... I could add that first link to the sidebar?

**Comment by marxo** [comment]
I agree that adding a link to the sidebar would help people track what they've read and what's new. There could also be a small "tag" on the pages showing which git version is currently online. The Rust project has one in the footer, so it is doable.

**Comment by davelab6** [comment]
http://static.rust-lang.org/doc/tutorial.html has a git commit hash but that refers to code, not the documentation page.

**Comment by davelab6** [comment]
https://github.com/fontforge/designwithfontforge.com/commit/c5b5524d24f8b9a72448349a39cffbe64b01b35e

**Comment by marxo** [comment]
If that git commit hash can't be printed just as a reference point for the readers, then this is the best solution there is. Thanks.

**Comment by JoesCat** [comment]
Nice to have, but unfortunately, requires someone to implement it, and someone to maintain it, and it only really helps those watching and waiting for results.

Anyone willing to help improve this book will have a pretty good idea of what needs doing within their capacity.

In summary,  seems like extra work distracting us from improving the book itself.
Closing this issue
