### ISSUE TITLE
PDF to have page numbers

### ISSUE THREAD

**Issue by davelab6** [fontforge/designwithfontforge.com#143]
https://www.facebook.com/fontforge/photos/a.178675055869594.1073741825.178674642536302/178675669202866/?type=3&comment_id=230398074030625&comment_tracking=%7B%22tn%22%3A%22R%22%7D
 says

> Todd Shandelman I hate to sound ungrateful, but the PDF format of the FontForge documentation available from the Website (http://designwithfontforge.com/.../design-with-fontforge...) is 252 pages. And there are NO PAGE NUMBERS in the pdf! In certain other cultures, this would be considered an evil joke. Is there any chance of getting page numbers in that puppy? Thanks. Todd, Houston, Texas

**Comment by jrbastien** [comment]
Fixed in this commit: 279927664eb407eb46aa2cbe464fd3c7203f04eb
