### ISSUE TITLE
http://designwithfontforge.com/en-US/Trusting_Your_Eyes.html

### ISSUE THREAD

**Issue by grinapo** [fontforge/designwithfontforge.com#147]
The result page contains a html-encoded string: "…½, **&amp;frac13;**, ¼…"

However the source doesn't seem to be faulty, so I guess this _entity_ is not really existing. I'd use unicode in the source but I see you haven't, possibly you have your nefarious reasons. :-)

**Comment by jrbastien** [comment]
That's curious, `&frac13;` is valid in markdown but not in html.
I just did some testing and unicode does not seem to be supported in Github's markdown.  I think the easiest way is simply to use the symbols directly like this ½, ⅓, ¼.

**Comment by jrbastien** [comment]
Thanks for reporting, this is now fixed.
