### ISSUE TITLE
Question: page weights

### ISSUE THREAD

**Issue by kayserifserif** [fontforge/designwithfontforge.com#166]
I'd like to contribute to the zh-TW translation, but I'm confused about the weight attribute in the Markdown files configuration sections. I've read through some documentation, but I don't understand what numbers to put, and why the numbers aren't consecutive in the weight lists. Are there pages missing in all language versions of the site?

Thank you!

**Comment by jrbastien** [comment]
Hi Katherine,  thanks for your contribution.  These weight lists are only there for reference.  They show how  chapters are organized in which order.  The numbering isn't consecutive to allow inserting new chapters in between.

Just use the english one as a reference:  https://github.com/fontforge/designwithfontforge.com/blob/gh-pages/en-US-weightlist.md

The weight that is important is the one that is the frontmatter of each individual chapter.  The pages will be dynamically rendered in this order. Of course,  for consistency the weightlist should bear the same numbers.

**Comment by kayserifserif** [comment]
Alright, thanks! I'll try it out 👍
