### ISSUE TITLE
Numbersign (#) glyph replacement issue

### ISSUE THREAD

**Issue by scottgit** [fontforge/designwithfontforge.com#178]
I originally thought this was a renaming issue. But further testing has proven otherwise.

It seems a glyph replacement on the **#** has an issue. If I enter the Metrics from the glyph editing window, it shows the new glyph. If I then remove it and retype it, it does not show, or if I type a second one to follow the first one, the original goes away and nothing shows. 

Additionally, if I type the **#** in the Metrics any _other glyphs following it_ do not show up, but those typed _before_ it _do_ keep displaying.

**Comment by frank-trampe** [comment]
@scottgit, this issue would best be filed under the fontforge repository. The metrics view looks up glyphs by their Unicode values, so your choice of encoding table and per-glyph encoding would both affect its behavior. It might be helpful to attach a file that exhibits the problem to the new post to facilitate testing.

**Comment by frank-trampe** [comment]
Oh gee. I read the e-mail from GitHub with the original issue text, but I did not read the rewritten text here. Handling of the hash sign changed a while ago; I'll need to investigate why. In the interim, you can refer to it by its glyph name, visible in the glyph info window, prefixed by a forward slash.

**Comment by scottgit** [comment]
@frank-trampe  So after you reread it, is it still a fontforge repository issue? Also, I did confirm that putting [/numbersign] or a renamed version of it does show the glyph in Metrics and allows following glyphs to work, so that is a work around.

**Comment by scottgit** [comment]
@frank-trampe You never replied to my last post. Should this be reopened?
