### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by tiktuk** [fontforge/designwithfontforge.com#19]
`hoohooo1.png`is missing from the section "Spacing, Metrics and Kerning".

**Comment by davelab6** [comment]
Yep its missing in the directory. @vernnobile do you have that image?

**Comment by vernnobile** [comment]
will fix. i see one more too :/

**Comment by davelab6** [comment]
Any luck with this? :)

**Comment by vernnobile** [comment]
Fixed.

**Comment by davelab6** [comment]
:dart:
