### ISSUE TITLE
Broken iframe in "Planning Your Project"

### ISSUE THREAD

**Issue by Yorwba** [fontforge/designwithfontforge.com#220]
The ["Overall Process" section of "Planning Your Project"](http://designwithfontforge.com/en-US/Planning_Your_Project.html#overall-process) embeds a [Google Doc](https://docs.google.com/file/d/0BxPD9osVW0s6SGNQRUs3ZmZrUzA/preview).

That doesn't work anymore. Google blocks embedding and the document itself has apparently been made private.
![iframe](https://user-images.githubusercontent.com/6555947/157126674-47d55f97-80f9-4277-b01b-d3c43eb36718.png)

I tried contacting the document owner to get access, but didn't receive any response so far.

**Comment by Yorwba** [comment]
Looks like the iframe was added by @davelab6 I hope you don't mind the ping. Do you still have the file?

**Comment by ctrlcctrlv** [comment]
If you don't hear back in 30 days I'd say it's reasonable to cut the section.

**Comment by jrbastien** [comment]
Here it is.  I used to be involved in ebooks creation and I see that the instructions on how to build them are no longer valid but I don't have time to contribute much.

The image needs to be placed in en-US/images/precompressed/.  If you could optimize the image using Grunt and update the link in the English and French versions to the optimized image, it would be appreciated.

![latin-typeface-design-process](https://user-images.githubusercontent.com/627071/158264179-a4c191ec-ba1c-40b5-b0de-37a2f8a2b5b6.png)

**Comment by Yorwba** [comment]
Thank you for the image!

**Comment by davelab6** [comment]
Amusingly I **just** came across this while going to show a collegue the image during a video call. The original said,

> This work is published at http://goo.gl/rxI63X with a Creative Commons Attribution-ShareAlike 3.0 licence. See also http://goo.gl/LJ8zm8

I recommend that the CC license text not be removed from the image, even though the whole site is under that license, to aid the image continuing to be used beyond this site. 

>> Google blocks embedding and the document itself has apparently been made private.

I don't understand either of these claims: 

The 2 links still work for me to load the source; not made private.

While I do see that somehow the "publish to web" setting was reset off - and so I have just turned it back on - I don't see any blocking. The Google Drawings UI just gave me these 2 embed HTML code examples at "large" size:

```
<img src="https://docs.google.com/drawings/d/e/2PACX-1vS0dPyM8Fs1Wu5N4VPQUdfzF9Lyg1qLGCy-uW9iAuk9khZVhxHTypylMHBT0JMS6q8beEOiFPoAdMJ0/pub?w=1228&amp;h=1428">

<img src="https://docs.google.com/drawings/d/e/2PACX-1vQRqkIslUMHc2QwQyPDLP3AUV783AZ_f9ISYpSr7KD60WIQBsEZfjzfrZFAzWWJnENbobm_FteHoFq6/pub?w=1228&amp;h=1428">
```

But still, having the /precompressed file is probably better anyway, so I'll make a PR to add the source link to the page by that image. 

Thanks all

**Comment by ctrlcctrlv** [comment]
Just noting my stunning accuracy for posterity ;-)

![image](https://user-images.githubusercontent.com/838783/161860712-661b4c4a-e325-4a54-ab32-5a6c3da3d2ce.png)

**Comment by davelab6** [comment]
Hahaha yes I saw that, pure luck on my part:)
