### ISSUE TITLE
Possible update for drawing with spiro

### ISSUE THREAD

**Issue by ahangarha** [fontforge/designwithfontforge.com#244]
Is this part of the book still relevant?

https://github.com/fontforge/designwithfontforge.com/blob/efdbd88e0aeb0b7c5ac63d604fda8b8799d61efd/en-US/Drawing_With_Spiro.md?plain=1#L9-L12

It seems FontForge currently supports the spiro tool by default.

**Comment by JoesCat** [comment]
You are correct, I believe it was converted to a 'required'.
