### ISSUE TITLE
What_Is_a_Font.html weighs in at over 8MB

### ISSUE THREAD

**Issue by garyritchie** [fontforge/designwithfontforge.com#31]
I recommend resampling the images used on this page at their final size/resolution to reduce the download size of this page. It may be that the author is not quite done finalizing this page.

Also, is there a shared space for the "working source" for images used on the site? This might be useful for making revisions later, allowing any contributor to use the original file to update an illustration or diagram rather than re-create from scratch.

**Comment by davelab6** [comment]
@vernnobile do you know where the image sources are?

**Comment by mozbugbox** [comment]
It seems that all the images have a maximum _render_ width of 690. Therefore it's possible to pre-scale the images down to less than 690 pixel on width.

The images are in en-US/images/

**Comment by garyritchie** [comment]
@davelab6 Should I be working in master or gh-pages branch?

@mozbugbox I wouldn't want to go less than their rendered size. I could batch process those that are _greater than_ render.

**Comment by davelab6** [comment]
@vernnobile ping :)

@garyritchie `gh-pages` is the live site. Master [should be deleted](http://matthew-brett.github.io/pydagogue/gh_delete_master.html)

**Comment by garyritchie** [comment]
@davelab6 perfect, thanks. Now everything's tidy.

**Comment by davelab6** [comment]
@garyritchie i added you to the website team, you should have full access now :)

**Comment by garyritchie** [comment]
Thanks, I'll try not to make a mess of things.

**Comment by davelab6** [comment]
Chatting to Girish Dalvi, I noted that "How formal elements are encultured / how culture is manifested through shapes and spaces between letters" is the secret shit no one teaches in design school, which this page should explain :)

**Comment by garyritchie** [comment]
Agreed. Do you know who might like to be invited to contribute that content?

To the point of this issue, I'm learning more about helpers like Grunt and
bower. I think grunt might help us create a set of reduced images during a
build routine so we can keep the originals intact.

**Comment by davelab6** [comment]
I'd love to see this site use grunt and bower

**Comment by davelab6** [comment]
Does that commite replace the images with lower quality ones?

**Comment by adrientetar** [comment]
No, it's all lossless. It gave large gains through, sometimes around 60%.

See https://gist.github.com/adrientetar/563b5b6c3ccf24db5660.

**Comment by davelab6** [comment]
AWESOME!

**Comment by garyritchie** [comment]
Nice work, Adrien!
