### ISSUE TITLE
Add links to examples of high quality FontForge font files

### ISSUE THREAD

**Issue by weiweihuanghuang** [fontforge/designwithfontforge.com#46]
This would be very useful, to see high quality FontForge source files. First ones I quickly found, with the help of usemodify.com are:

Foundries / Collections:
- [Omnibus](https://github.com/Omnibus-Type/)
- [OSP Foundry](http://ospublish.constantvzw.org/foundry/)
- [Ralph Levien](http://levien.com/type/myfonts/)
- [VTF](http://velvetyne.fr/) some of these
- [Jason Reed](http://jcreed.org/fonts/)

Typefaces and Fonts:
- [Anka](https://code.google.com/p/anka-coder-fonts/source/browse/#hg%2FAnkaCoder%253Fstate%253Dclosed)
- [Tuffy](http://tulrich.com/fonts/)
- [Whois Mono](https://github.com/raphaelbastide/Whois-mono/)
- [Liberation](https://fedorahosted.org/liberation-fonts/)
- [Fantasque Sans Mono](https://github.com/belluzj/fantasque-sans)
- [DejaVu Fonts](http://dejavu-fonts.org/)
- [Bluu](http://velvetyne.fr/#bluu)

Not sure about the quality (e.g. completeness, features and diacritics?) of all of these.

Edit \* accidentally closed the issue *

**Comment by JoesCat** [comment]
Thanks @weiweihuanghuang for these links.
I've added them to "Further Reading".
