### ISSUE TITLE
Set up eBook build system

### ISSUE THREAD

**Issue by davelab6** [fontforge/designwithfontforge.com#5]
www.github.com/progit/progit has a PDF/ePub/Mobi build system, which should be copied over to here :)

**Comment by JohnWong** [comment]
It is interesting. I will try it later.

**Comment by JohnWong** [comment]
I have tried to put this book on Gitbook, which is a outstanding e-book build system. It seems to be more suitable for reading. PDF/ePub/Mobi is also available on the first page. See [Design With FontForge](http://yellowxz.gitbooks.io/designwithfontforge/). Should we change our build system from Jekyll to Gitbook, or just use Gitbook as a PDF/ePub/Mobi generator.

**Comment by davelab6** [comment]
I'd prefer to keep Jekyll as it's live and can work totally online. Gitbook
for the eBook formats is great!

**Comment by JohnWong** [comment]
It's done. I may rebuild e-books every month.

**Comment by davelab6** [comment]
Maybe we could move the sources to the master branch and use Travis to run
the jeykll compilation plus this tool to generate the pdf, and push the
result into the gh-pages branch?
