### ISSUE TITLE
About Traditional Chinese Translation

### ISSUE THREAD

**Issue by chengluyu** [fontforge/designwithfontforge.com#52]
When I go to homepage of [designwithfont.com](http://designwithfontforge.com/en-US/index.html), I see both English and Traditional Chinese content. They should be separated into two pages, shouldn't they?
![default](https://cloud.githubusercontent.com/assets/2239547/4693163/184fa7ca-578e-11e4-97fc-1ab578ca9dcb.PNG)

**Comment by jtanx** [comment]
See #49

**Comment by tshinnic** [comment]
? Does that mean "We're working on it - please ignore the duplication until we've gotten that sorted out?"

**Comment by jtanx** [comment]
Well this issue is covered in issue #49, making this a duplicate.

So... please continue discussion in that one instead?

**Comment by chengluyu** [comment]
@jtanx, thanks for your help, I should have read previous issues before asking.

**Comment by chengluyu** [comment]
@jtanx, by the way, I also want to contribute my Simplified Chinese translation, so what I need to do is just fork, commit and send pull request?

**Comment by jtanx** [comment]
Yes I believe so. Thanks!

**Comment by adrientetar** [comment]
@chengluyu FYI, chinese translation was updated.

**Comment by chengluyu** [comment]
Wow! I am still working on my version for I spend much time polishing my translation to make it readable.

Anyway, it is amazing to see the Simplified Chinese translation coming out.

--- 原始邮件 ---

发件人： "Adrien Tétar" notifications@github.com
已发： 2014年11月26日 上午12:48
收件人： "fontforge/designwithfontforge.com" designwithfontforge.com@noreply.github.com
抄送： "Cheng Luyu" chengluyu@live.cn
主题： Re: [designwithfontforge.com] About Traditional Chinese Translation (#52)

@chengluyu FYI, chinese translation was updated.

---

**Comment by zerng07** [comment]
I believe tha you can communicate with him to improve the translation and work as a team. :)

**Comment by chengluyu** [comment]
I'd like to. :-)

--- 原始邮件 ---

发件人： "zerng07" notifications@github.com
已发： 2014年11月26日 下午12:51
收件人： "fontforge/designwithfontforge.com" designwithfontforge.com@noreply.github.com
抄送： "Cheng Luyu" chengluyu@live.cn
主题： Re: [designwithfontforge.com] About Traditional Chinese Translation (#52)

I believe tha you can communicate with him to improve the translation and work as a team. :)

---

**Comment by davelab6** [comment]
I recommend working publicly to avoid duplicate effort - is okay to work
live on the site with a disclaimer :)

**Comment by adrientetar** [comment]
Or on a fork.

**Comment by JohnWong** [comment]
Happy to see more volunteers. My work is not good enough. Looking forward to chengluyu's translation.

**Comment by davelab6** [comment]
On 26 November 2014 at 17:26, Adrien Tétar notifications@github.com wrote:

> Or on a fork.

I doubt anyone looks at them
