### ISSUE TITLE
Page–to–Page navigation

### ISSUE THREAD

**Issue by urcades** [fontforge/designwithfontforge.com#73]
As it stands for most pages, a reader needs to scroll up to the top in order to navigate to the next chapter. (or any chapter for that matter)

To ease the reading experience, it'd be beneficial to add chapter-to-chapter navigation at the bottom of the various pages.

Just a small thought!

**Comment by chakler** [comment]
This issue should be closed :smiley:

**Comment by JohnWong** [comment]
Well done!
