### ISSUE TITLE
Image doesn't exists

### ISSUE THREAD

**Issue by chakler** [fontforge/designwithfontforge.com#78]
The image in the _Decoration_ section of _What Is A Font?_ page doesn't exists. 

![screen shot 2015-03-31 at 2 43 07 pm](https://cloud.githubusercontent.com/assets/3196969/6913547/51708154-d7b4-11e4-8c56-ee97d66cf415.png)

**Comment by davelab6** [comment]
@monkeyiq @nwillis @EbenSorkin do you have an image with filename `4decoration.png` anywhere? :)

**Comment by EbenSorkin** [comment]
I'll check

**Comment by aryelgois** [comment]
Hey there

It still doesn't exist

**Comment by davelab6** [comment]
I guess it needs to be recreated based on the description

**Comment by EbenSorkin** [comment]
Looking at the context this probably came from a Crafting Type talk. I'll see if I can figure out what it was later today. If I don't find it quickly I'll take a photo from my library which is making the relevant point and supply that.

**Comment by davelab6** [comment]
@aryelgois Eben found them and I made a pull request but I think it needs a little more work to be ready.... do you know how to prepare/optimize the images?

**Comment by EbenSorkin** [comment]
I can also alter them if I have a target to aim for. The other images might
be a good guide. Are they?

-e.

**Comment by jrbastien** [comment]
I'm busy right now but if you can't compressed them, I will eventually.  Just follow the instructions in the readme:

How to compress images with Grunt

Put all the raw images inside en-US/images/precompressed/

Make sure npm is already installed in your computer, then install all the dependencies with:

npm install

Once the installations are done, you can go ahead to minify all the images with this Grunt command:

grunt

Wait for Grunt to notify you, and all the compressed images will be inside en-US/images/

**Comment by aryelgois** [comment]
@davelab6 i can take a moment and learn :) where is the image?
