### ISSUE TITLE
Chapter 6.5 Introduction to the interface

### ISSUE THREAD

**Issue by larsenwork** [fontforge/designwithfontforge.com#85]
It currently jumps directly from installing it to how to use the drawing tools. 

I think novice users would benefit from a more general introduction to the interface.

**Comment by davelab6** [comment]
Yeah, my "introduction to fontforge" video on YouTube for crafting type in
Sweden a couple years ago should be good for this

**Comment by larsenwork** [comment]
Haven't seen it but based on the title of the video I'd agree. 

And on a general note - all novice subjects should have videos. 

A video explaining chapter 7 would be a lot better than text.
