### ISSUE TITLE
Add fonts made with FontForge section

### ISSUE THREAD

**Issue by pathumego** [fontforge/designwithfontforge.com#94]
There is a list of fonts made with Fontforge here : http://en.wikipedia.org/wiki/FontForge

We should link to sources/ repos of these fonts and maybe add this to Further Reading.

**Comment by larsenwork** [comment]
Good idea with linking - I think we should only be linking to projects that are open source though - these projects will be most beneficial to explore for the readers.

**Comment by pathumego** [comment]
Yep, lets just add the open source projects. in connection to #95, where should these go?

**Comment by JoesCat** [comment]
Added to SFD Font list in "Further Reading".
Done.
